package com.infy.lcp.entity;

public enum NewsCategory {
	EDUCATIONAL, CRIME, GEOPOLITICS, NATIONAL, SPORTS, HEALTH, LIFESTYLE, EDITORIALS, ENTERTAINMENT, TECHNOLOGY, BUSINESS, SPIRITUAL, CULTURE, GENERAL
}
